Run Information
========================
cognizant.intelligent.test.scripter.engine : 1.4
java.runtime.name    : Java(TM) SE Runtime Environment
java.version         : 11.0.8
java.home            : C:\Program Files\Java\jdk-11.0.8
os.name              : Windows 10
os.arch              : amd64
os.version           : 10.0
file.encoding        : UTF-8
========================
Run Started on Fri Oct 09 16:52:45 BST 2020
Loading Browser Profile
Loading RunManager
[Scenario:Home EAgro] [TestCase: Verify Analytics_ProcessMetrics] [Description: Verify Analytics_ProcessMetrics] [Browser: Chrome Headless] [BrowserVersion: Default] [Platform: ANY][ExistingBrowser: false]
----------------------------------------------------------
[1] TestCase selected for execution from [//Appian Demo Suits/Demo Session]
----------------------------------------------------------
Initializing Report
ApiLink not available!!
Run Manager true
Continue Execution true
Shutting Down Thread as there is no need for SelectiveThreading
Inside Task Run
Running Iteration 1
Launching Chrome Headless
Launching Local Driver
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 17111
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1602258766.048][WARNING]: This version of ChromeDriver has not been tested with Chrome version 86.
2020-10-09 16:52:48:10S +0100 [INFO] org.openqa.selenium.remote.ProtocolHandshake createSession:Detected dialect: W3C
Chrome Headless Launched
Step:1   | Object: Browser | Action: Open | Input: Verify Analytics_ProcessMetrics:URL | Conditon:  | @09-Oct-2020 16:52:48.048
Breaking subIteration, End Of Input!!
2020-10-09 16:52:48:10S +0100 [SEVERE] com.cognizant.cognizantits.engine.core.Task onError:Error in testcase [//Home EAgro/Verify Analytics_ProcessMetrics]
com.cognizant.cognizantits.engine.execution.exception.TestFailedException: Error in testcase [//Home EAgro/Verify Analytics_ProcessMetrics]
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:362)
	at com.cognizant.cognizantits.engine.core.Task.runIteration(Task.java:130)
	at com.cognizant.cognizantits.engine.core.Task.run(Task.java:85)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: Test Data Not Found, SubIteration - 1:1 is missing. 
[Env : Default | Sheet : Verify Analytics_ProcessMetrics | Field : URL | TestCase : Home EAgro/Verify Analytics_ProcessMetrics ]
	at com.cognizant.cognizantits.engine.execution.data.DataAccessInternal.throwErrorWithCause(DataAccessInternal.java:292)
	at com.cognizant.cognizantits.engine.execution.data.DataAccess.getData(DataAccess.java:71)
	at com.cognizant.cognizantits.engine.execution.data.DataProcessor.resolve(DataProcessor.java:64)
	at com.cognizant.cognizantits.engine.core.CommandControl.sync(CommandControl.java:168)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.executeStep(TestStepRunner.java:160)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.executeStep(TestStepRunner.java:147)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.run(TestStepRunner.java:66)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.runStep(TestCaseRunner.java:395)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:346)
	... 5 more

[DEBUG]   | Error in testcase [//Home EAgro/Verify Analytics_ProcessMetrics]

===================================================================================================


---------------------------------------------------
Testcase Name        : Home EAgro:Verify Analytics_ProcessMetrics
Executed Steps       : 1
Passed Steps         : 0
Failed Steps         : 1
Time Taken           : 00:00:03
-----------------------------------------------------

Run Finished on Fri Oct 09 16:52:48 BST 2020
-----------------------------------------------------
ExecutionDate        : 09-Oct-2020 16-52-45
Executed TestCases   : 1
Passed TestCases     : 0
Failed TestCases     : 1
Time Taken           : 00:00:03
ReportPath           : file:///C:\Working\Automation\cognizant-intelligent-test-scripter-1.4-setup\AppianEuropeConf\Projects\Appian Europe Conference\Results\TestExecution\Appian Demo Suits\Demo Session\09-Oct-2020 16-52-45\summary.html
-----------------------------------------------------
